name: Manual workflow

on:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run wdio

      - name: Set Environment Variables
        run: |
          echo "LAST_RUN=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          echo "STATUS=Passed" >> $GITHUB_ENV
          echo "TEST_RESULTS=20/20" >> $GITHUB_ENV

      - name: Generate CI Status Badge
        uses: alvivi/shield-badge@v1
        with:
          label: "Last test execution"
          text: "Última execução: ${{ env.LAST_RUN }} - ${{ env.STATUS }} (Tests: ${{ env.TEST_RESULTS }})"
      
