name: Manual workflow

on:
  workflow_dispatch:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run wdio

      - name: Atualizar README com informações do CI
        run: |
          LAST_RUN=$(date +"%Y-%m-%d %H:%M:%S")
          STATUS="Todos os testes passaram"
          sed -i "s/<!-- CI_STATUS: placeholder -->/<!-- CI_STATUS: --> Última execução: $LAST_RUN - $STATUS/g" README.md

      - name: Configurar credenciais Git e atualizar remote
        run: |
          git config --local user.email "1222013@isep.ipp.pt"
          git config --local user.name "Paulojft94"
          git remote set-url origin https://x-access-token:${{secrets.MY_PAT}}@github.com/Paulojft94/webdriverIO.git

      - name: Commit e Push da atualização no README
        run: |
          git add README.md
          git commit -m "Atualiza status do CI no README [skip ci]"
          git push
